### ISSUE TITLE
'runterra2' 오류

### ISSUE THREAD

**Issue by moonjy1120** [J-hoplin1/League-Of-Legend-Search-Bot#2]
2020년 5월3일 현재 배너에 있는 
img src="//opgg-static.akamaized.net/images/banner/runterra2_opgg_small.png" class="opgg-header__image_banner-icon-img"
이부분이 코드상에
RankMedal = soup.findAll('img', {'src': re.compile('\/\/[a-z]*\-[A-Za-z]*\.[A-Za-z]*\.[A-Za-z]*\/[A-Za-z]*\/[A-Za-z]*\/[a-z0-9_]*\.png')})
에서 오류를 발생기키고 있습니다.

**Comment by moonjy1120** [comment]
Medal = bs.find('div', {'class': 'ContentWrap tabItems'})
  RankMedal = Medal.findAll('img', {'src': re.compile('\/\/[a-z]*\-[A-Za-z]*\.[A-Za-z]*\.[A-Za-z]*\/[A-Za-z]*\/[A-Za-z]*\/[a-z0-9_]*\.png')})
로 처리하여 앞으로도 배너이미지에 있는건 추출하지 않게 하였습니다

**Comment by J-Hoplin** [comment]
안녕하세요 moonjy1120님! 우선 제 디스코드 봇에 관심을 가져주시고 오류를 찾아주셔서 진심으로 감사합니다. 제가 생각하지도 못한곳에서 오류가 났군요... 해당 부분을 찾아주셔서 진심으로 감사드립니다.오늘내로 코드를 수정하여 커밋하겠습니다. 제 코드의 오류를 찾아주신 만큼 contributor로 등록해 드리고 싶습니다. 혹시 contributor로 등록해 드려도될까요?

**Comment by J-Hoplin** [comment]
우선 해당 이슈부분을 다시 수정하여 커밋해놓았습니다 :)

**Comment by moonjy1120** [comment]
감사합니다^^ 물론이죠 등록하셔도 됩니다. 연휴 잘 보내세요~
(moonjy1120@naver.com)

**Comment by J-Hoplin** [comment]
추가해드렸습니다 :D 좋은하루되세요!!
