### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by dongsu8142** [J-hoplin1/League-Of-Legend-Search-Bot#3]
세로운 코드로 하니까 오류가 생깁니다 원래는 없었는데

**Comment by dongsu8142** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\BEOMSOO\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "c:/Users/BEOMSOO/Desktop/lolbot/bot.py", line 216, in on_message
    solorankmedal = RankMedal[0]['src'].split('/')[-1].split('?')[0].split('.')[0].split('_')
IndexError: list index out of range

**Comment by J-Hoplin** [comment]
안녕하세요 hands8142님 현재 제 디스코드 api의 오류로 인해 현재로서는 확인을 해드릴수 없어서 죄송합니다. 우선 이전 버전으로 롤백하시고 싶으신 경우(https://github.com/J-hoplin1/League-Of-Legend-Search-Bot/tree/Base-Version) 여기에 있는 파이썬 코드를 사용해 주시기 바랍니다. 오류가 해결되는대로 확인해서 해결책을 알려드리겠습니다

**Comment by dongsu8142** [comment]
아 오류가 확인되어서 이미 롤백했습니다

**Comment by dongsu8142** [comment]
친절한답변 감사합니다

**Comment by J-Hoplin** [comment]
hands8142님! 오류가 지금 해결되어서 답변을 드립니다. 어제자 패치에서 
`Medal = bs.find('div', {'class': 'ContentWrap tabItems'})
RankMedal = Medal.findAll('img', {'src': re.compile('//[a-z]-[A-Za-z].[A-Za-z].[A-Za-z]/[A-Za-z]/[A-Za-z]/[a-z0-9_]*.png')})`

다음과 같이 코드를 변경했었는데요, 이 코드는 배너광고 이미지를 긁어오는 경우가 발생할수 있어서 추후 유지보수를 고려하여 변경하게 되었었습니다. 다만 제 노트북 3대로 테스트를 해본 결과 'ContentWrap tabItems' 이 부분의 띄어쓰기(White Blank)를 PC 환경설정, Python 환경설정 혹은 OS플랫폼에 따라서 인식하기도 하고, 인식하지 못하기도 한다는것을 확인하였습니다. 오늘 패치에서는 다음과 같은점이 변경되었습니다.

1. 알고리즘 변경 : 알고리즘이 다소 변경 되었습니다. 처리 속도가 조금 더 빨라졌습니다.

2. 위에 언급해 드린 부분에 대해서 조금 더 명확한 정의를 주기 위해 다음과 같이 변수 조정을 하였습니다.
`Medal = bs.find('div', {'class': 'SideContent'})
RankMedal = Medal.findAll('img', {'src': re.compile('\/\/[a-z]*\-[A-Za-z]*\.[A-Za-z]*\.[A-Za-z]*\/[A-Za-z]*\/[A-Za-z]*\/[a-z0-9_]*\.png')})` 

방금 패치된 코드를 사용하시면 위의 패치노트가 적용됩니다. 항상 제 디스코드 봇 코드에 관심을 주시고 의견을 제시해주셔서 감사합니다 :)

**Comment by dongsu8142** [comment]
감사합니다
